# Generated by Django 5.2.15 on 2026-06-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph_type', models.CharField(choices=[('root', 'Корень'), ('prefix', 'Префикс'), ('suffix', 'Суффикс'), ('infix', 'Инфикс'), ('ending', 'Окончание'), ('alternation', 'Фонетическое чередование')], max_length=20)),
                ('surface', models.CharField(max_length=50)),
                ('underlying', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('alternation_rule', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LexiconEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexicon_name', models.CharField(max_length=100)),
                ('input_pattern', models.CharField(max_length=200)),
                ('output_pattern', models.CharField(max_length=200)),
                ('next_lexicon', models.CharField(blank=True, max_length=100)),
                ('morpheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='morph.morpheme')),
            ],
        ),
        migrations.AddField(
            model_name='morpheme',
            name='adds_tags',
            field=models.ManyToManyField(blank=True, related_name='added_by', to='morph.tag'),
        ),
        migrations.AddField(
            model_name='morpheme',
            name='tags',
            field=models.ManyToManyField(blank=True, to='morph.tag'),
        ),
    ]
