# Generated by Django 5.2.15 on 2026-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='gloss',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
