# Generated by Django 4.2.1 on 2026-02-07 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код (напр., avar)')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('family', models.CharField(max_length=50, verbose_name='Семья')),
                ('is_ergative', models.BooleanField(default=False, verbose_name='Эргативный строй')),
                ('is_agglutinative', models.BooleanField(default=True, verbose_name='Агглютинативный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Affix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affix', models.CharField(max_length=50, verbose_name='Аффикс')),
                ('affix_type', models.CharField(choices=[('suffix', 'Суффикс'), ('prefix', 'Префикс')], max_length=10, verbose_name='Тип')),
                ('grammatical_value', models.CharField(max_length=50, verbose_name='Грамм. значение')),
                ('position', models.IntegerField(default=0, help_text='Порядок в слове (0 сразу после корня)')),
                ('examples', models.TextField(blank=True, verbose_name='Примеры')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.language', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=200, verbose_name='Корень')),
                ('gloss', models.CharField(max_length=300, verbose_name='Основной перевод')),
                ('pos', models.CharField(choices=[('noun', 'Существительное'), ('verb', 'Глагол'), ('adj', 'Прилагательное')], max_length=20, verbose_name='Часть речи')),
                ('noun_class', models.CharField(blank=True, help_text='Напр.: I (в-), II (й-), III (б-), IV (р-) для аварского', max_length=10, verbose_name='Именной класс')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник записи')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.language', verbose_name='Язык')),
            ],
            options={
                'unique_together': {('root', 'language')},
            },
        ),
    ]
